name: mclip_cli
description: command-line interface for mclip.
repository: https://github.com/mint-tube/mclip-cli

platforms:
  linux:
  macos: # ???

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.5.0
