name: metaclip_cli
description: command-line interface for metaclip.
repository: https://github.com/mint-tube/metaclip-cli

platforms:
  linux:
  macos: # ???

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.5.0
  path: ^1.9.0
